apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ebpf-iomon
allowPrivilegedContainer: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: true
allowedCapabilities:
  - BPF
  - PERFMON
  - SYS_RESOURCE
readOnlyRootFilesystem: true
requiredDropCapabilities:
  - ALL
defaultAddCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:ebpf-iomon:ebpf-iomon
volumes:
  - hostPath
  - configMap
  - secret
  - emptyDir
