apiVersion: v1
kind: Service
metadata:
  name: ebpf-iomon
  namespace: ebpf-iomon
  labels:
    app.kubernetes.io/name: ebpf-iomon
    app.kubernetes.io/component: agent
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: ebpf-iomon
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
